<a href="https://colab.research.google.com/github/mk7ossen/introduction_to_programming_with_python/blob/main/PP_02_20_Mohammad_Kawsar_Hossen_final_exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Question 1


In [ ]:
employee_score = int(input("Enter your score: "))

if (employee_score >= 90) and (employee_score <= 100):
  print("Your score is excellent")

elif (employee_score >= 80) and (employee_score <= 89):
  print("Your score is very good")

elif (employee_score >= 70) and (employee_score <= 79):
  print("Your score is good")

elif (employee_score >= 60) and (employee_score <= 69):
  print("Your score is satisfactory")

elif employee_score < 60:
  print("Needs Improvement")



Enter your score: 101


##Question 2

In [ ]:

#a

while True:
    try:
#b
        n = int(input("Enter a positive integer: "))
        print()
        if n <= 0:
#d
            print("Invalid input. Please enter a positive integer.")
            print()
            continue

        sum_of_odds = 0
        i = 1
        while i <= n:
            if i % 2 != 0:
                sum_of_odds += i
            i += 1

#c
        print(f"The sum of all odd numbers between 1 and {n} is: {sum_of_odds}")
        print()
        break
    except ValueError:
        print("Invalid input. Please enter a valid positive integer.")


Enter a positive integer: -10

Invalid input. Please enter a positive integer.

Enter a positive integer: 10

The sum of all odd numbers between 1 and 10 is: 25




##Question 3

In [ ]:
#a
 # we import the re package when working with Regular Expression


#b
import re

x = "banana"
positions = [m.start() for m in re.finditer('a', x)]
print("Positions of 'a':", positions)


#c
y = "Life is what happens when you're busy making other plans"
new_string = re.sub(r'\bwhat\b', 'where', y)
print("Modified string:", new_string)

Positions of 'a': [1, 3, 5]
Modified string: Life is where happens when you're busy making other plans


##Question 4

In [ ]:
import os

#a
with open("notes.txt", "w") as file:
    file.write("")
print("File 'notes.txt' created.")

#b
with open("notes.txt", "a") as file:
    file.write("Programming is an essential skill in today's world.\n")


with open("notes.txt", "r") as file:
    content = file.read()
print("\nContents of 'notes.txt':")
print(content)

#c
if os.path.exists("notes.txt"):
    os.remove("notes.txt")
    print("\nFile 'notes.txt' deleted.")
else:
    print("\nFile does not exist!")


File 'notes.txt' created.

Contents of 'notes.txt':
Programming is an essential skill in today's world.


File 'notes.txt' deleted.


Question 5

In [ ]:
import numpy as np

#a
array = np.random.randint(5, 16, size=(3, 3))
print("Original Array:")
print(array)

#b
transpose_array = array.T
print("\nTranspose of the Array:")
print(transpose_array)

#c
sum_elements = np.sum(array)
print("\nSum of all elements in the array:", sum_elements)

#d
indices = np.argwhere(array > 10)
print("\nIndices of elements greater than 10:")
print(indices)


Original Array:
[[ 7 11  6]
 [14 15 10]
 [12 15  5]]

Transpose of the Array:
[[ 7 14 12]
 [11 15 15]
 [ 6 10  5]]

Sum of all elements in the array: 95

Indices of elements greater than 10:
[[0 1]
 [1 0]
 [1 1]
 [2 0]
 [2 1]]
